<?php $h=  $this->getRequest()->getFullActionName(); if($h == 'cms_index_index'){?>
<div class="margin_collapsetop"></div>
<div id="ttr_slideshow_inner">
<ul>
<li id="Slide0" class="ttr_slide" data-slideEffect="None">
<div class="ttr_slideshow_last">
<div class="ttr_slideshow_element_alignment container" data-begintime="0" data-effect="None" data-easing="linear" data-slide="None" data-duration="0">
</div>
</div>
</li>
<li id="Slide1" class="ttr_slide" data-slideEffect="None">
<a href="http://templatetoaster.com/"></a>
<div class="ttr_slideshow_last">
<div class="ttr_slideshow_element_alignment container" data-begintime="0" data-effect="None" data-easing="linear" data-slide="None" data-duration="0">
</div>
</div>
</li>
</ul>
</div>
<div class="ttr_slideshow_in">
<div class="ttr_slideshow_last">
<div class="ttr_slideshow_element_alignment container">
</div>
<div id="nav"></div>
<div class="ttr_slideshow_logo">
</div>
<div class="ttr_stickyslideshowshape1">
<div class="html_content"><p><span><a href="http://templatetoaster.com" target="_self" class="btn btn-md btn-default">Order Now</a></span></p></div>
</div>
<div class="ttr_stickyslideshowshape2">
<div class="html_content"><p style="text-align:Right; display:block; line-height:5em;"><span style="font-family:'Overlock','Arial';font-size:4.286em;color:rgba(245,93,127,1);">To Share a Flower is </span></p><p style="text-align:Right; display:block; line-height:5em;"><span style="font-family:'Overlock','Arial';font-size:4.286em;color:rgba(245,93,127,1);">Share the happiness</span></p></div>
</div>
</div>
</div>
<?php } ?>
